// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNTlB_qCE1fi_hyQdQZeY_hEPI2xzzCFs',
    appId: '1:699988950825:web:4944294d1e6ee5ee944138',
    messagingSenderId: '699988950825',
    projectId: 'ddm-api-rest',
    authDomain: 'ddm-api-rest.firebaseapp.com',
    databaseURL: 'https://ddm-api-rest-default-rtdb.firebaseio.com',
    storageBucket: 'ddm-api-rest.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxLumA5byXmnAObmO7haOUKffq9kF-UbM',
    appId: '1:699988950825:android:97a5bc1822b779ef944138',
    messagingSenderId: '699988950825',
    projectId: 'ddm-api-rest',
    databaseURL: 'https://ddm-api-rest-default-rtdb.firebaseio.com',
    storageBucket: 'ddm-api-rest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7dQuZFyG0EGXnF-fbGU3LuM0x3P61XR0',
    appId: '1:699988950825:ios:c88daddfd510cf78944138',
    messagingSenderId: '699988950825',
    projectId: 'ddm-api-rest',
    databaseURL: 'https://ddm-api-rest-default-rtdb.firebaseio.com',
    storageBucket: 'ddm-api-rest.firebasestorage.app',
    iosBundleId: 'com.example.ddmProjetoFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7dQuZFyG0EGXnF-fbGU3LuM0x3P61XR0',
    appId: '1:699988950825:ios:c88daddfd510cf78944138',
    messagingSenderId: '699988950825',
    projectId: 'ddm-api-rest',
    databaseURL: 'https://ddm-api-rest-default-rtdb.firebaseio.com',
    storageBucket: 'ddm-api-rest.firebasestorage.app',
    iosBundleId: 'com.example.ddmProjetoFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNTlB_qCE1fi_hyQdQZeY_hEPI2xzzCFs',
    appId: '1:699988950825:web:af36aeca21ce1c5e944138',
    messagingSenderId: '699988950825',
    projectId: 'ddm-api-rest',
    authDomain: 'ddm-api-rest.firebaseapp.com',
    databaseURL: 'https://ddm-api-rest-default-rtdb.firebaseio.com',
    storageBucket: 'ddm-api-rest.firebasestorage.app',
  );
}
